language:
  - python

python:
  - 3.6

install:
  - pip install -r requirements.txt

script:
  - pycodestyle --ignore=E501 skde/lag_format.py
  - pycodestyle --ignore=E501 skde/legg_til_nye_formater.py

notifications:
  email: false
